FROM php:8.3-cli-alpine

WORKDIR /sdk

RUN apk add --no-cache curl unzip \
    && curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer

COPY composer.json composer.lock* ./
RUN composer install --no-interaction --prefer-dist --no-progress

COPY src/ src/
COPY tests/ tests/

CMD ["./vendor/bin/phpunit", "--testdox", "tests/"]
